### ISSUE TITLE
About the value interpretation

### ISSUE THREAD

**Issue by Linnaeus001** [Yangcq-Ivy/NicheBarcoding#1]
Hi Yang, thanks so much for your works!

I've tried the NBSI2 function on my dataset but only got these result: P(Bk), min(P(EK)), P(Ek), Prob(Sid).TSI, Prob(Sid).CI.unc. It's said that P(Ek) is "The membership probability of the unknown sample belongs to the species k based on the ecological niche model", so I guess in Scenario 1, that's the things we want to check for species identification right? I wonder if it's normal that my P(Ek) is reletively low (<0.6). Thanks again if you can help :)

Best,
Tang

**Comment by Yangcq-Ivy** [comment]
Dear Tang,

Thank you very much for choosing the NicheBarcoding package for your analysis, and we welcome any suggestions for improving it.

In my view, the method you used to run Scenario1 is correct, and there is no issue with the interpretation of the results regarding P(Ek). In fact, P(Ek) is an intermediate result, and our function has further transformed it, so you can use the **Prob(Sid)** results to obtain the final species identification reliability values. P(Ek) has different thresholds for different species and can be used as a relative reference rather than an absolute value for judgment.

Of course, we have updated the function to make these results more concise and readable. We strongly recommend that you download and install the latest version from GitHub (the current one is it). In the new version's output, you can take the last column **NBSI.prob** as your final judgment.

Thank you again for your question.

Best wishes,
Cai-qing

**Comment by Yangcq-Ivy** [comment]
> Hi Yang, thanks so much for your works!
> 
> I've tried the NBSI2 function on my dataset but only got these result: P(Bk), min(P(EK)), P(Ek), Prob(Sid).TSI, Prob(Sid).CI.unc. It's said that P(Ek) is "The membership probability of the unknown sample belongs to the species k based on the ecological niche model", so I guess in Scenario 1, that's the things we want to check for species identification right? I wonder if it's normal that my P(Ek) is reletively low (<0.6). Thanks again if you can help :)
> 
> Best, Tang

Dear Tang,

Thank you very much for choosing the NicheBarcoding package for your analysis, and we welcome any suggestions for improving it.

In my view, the method you used to run Scenario1 is correct, and there is no issue with the interpretation of the results regarding P(Ek). In fact, P(Ek) is an intermediate result, and our function has further transformed it, so you can use the Prob(Sid) results to obtain the final species identification reliability values. P(Ek) has different thresholds for different species and can be used as a relative reference rather than an absolute value for judgment.

Of course, we have updated the function to make these results more concise and readable. We strongly recommend that you download and install the latest version from GitHub (the current one is it). In the new version's output, you can take the last column NBSI.prob as your final judgment.

Thank you again for your question.

Best wishes,
Cai-qing

**Comment by Linnaeus001** [comment]
> > Hi Yang, thanks so much for your works!
> > I've tried the NBSI2 function on my dataset but only got these result: P(Bk), min(P(EK)), P(Ek), Prob(Sid).TSI, Prob(Sid).CI.unc. It's said that P(Ek) is "The membership probability of the unknown sample belongs to the species k based on the ecological niche model", so I guess in Scenario 1, that's the things we want to check for species identification right? I wonder if it's normal that my P(Ek) is reletively low (<0.6). Thanks again if you can help :)
> > Best, Tang
> 
> Dear Tang,
> 
> Thank you very much for choosing the NicheBarcoding package for your analysis, and we welcome any suggestions for improving it.
> 
> In my view, the method you used to run Scenario1 is correct, and there is no issue with the interpretation of the results regarding P(Ek). In fact, P(Ek) is an intermediate result, and our function has further transformed it, so you can use the Prob(Sid) results to obtain the final species identification reliability values. P(Ek) has different thresholds for different species and can be used as a relative reference rather than an absolute value for judgment.
> 
> Of course, we have updated the function to make these results more concise and readable. We strongly recommend that you download and install the latest version from GitHub (the current one is it). In the new version's output, you can take the last column NBSI.prob as your final judgment.
> 
> Thank you again for your question.
> 
> Best wishes, Cai-qing

Thanks, it's work!

**Comment by Linnaeus001** [comment]
Thanks, it works! It seems that CRAN's is not updated yet :)
